package com.mohamadhh.goldenclover;
import android.app.Instrumentation;import android.app.Activity;import android.content.Intent;import android.os.Bundle;import android.os.SystemClock;import android.graphics.Bitmap;import android.view.MotionEvent;import android.view.ViewGroup;
import com.mohamadhh.goldenclover.game.*;
import java.io.File;import java.io.FileOutputStream;import java.lang.reflect.Field;
/** Real-device portrait input, packaged audio and session lifecycle verification. */
public final class SmokeInstrumentation extends Instrumentation {
 private GoldenCloverView view;private GameState state;private String preset;private File directory;
 @Override public void onCreate(Bundle args){super.onCreate(args);preset=args.getString("preset","16x9");start();}
 private void check(boolean b,String message){if(!b)throw new AssertionError(message);}
 private void tap(float x,float y)throws Exception{final float[] point=new float[2];runOnMainSync(()->{try{Field f=GoldenCloverView.class.getDeclaredField("layout");f.setAccessible(true);ResponsiveLayout l=(ResponsiveLayout)f.get(view);point[0]=l.left+x*l.scale;point[1]=l.top+y*l.scale;}catch(Exception e){throw new RuntimeException(e);}});long t=SystemClock.uptimeMillis();MotionEvent down=MotionEvent.obtain(t,t,MotionEvent.ACTION_DOWN,point[0],point[1],0),up=MotionEvent.obtain(t,t+60,MotionEvent.ACTION_UP,point[0],point[1],0);down.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);up.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(down,true),"touch down");check(getUiAutomation().injectInputEvent(up,true),"touch up");down.recycle();up.recycle();SystemClock.sleep(150);}
 private void shot(String name)throws Exception{Bundle progress=new Bundle();progress.putString("stream","CAPTURE "+preset+" "+name+"\n");sendStatus(1,progress);SystemClock.sleep(250);Bitmap b=getUiAutomation().takeScreenshot();check(b!=null,"screenshot available");try(FileOutputStream out=new FileOutputStream(new File(directory,preset+"-"+name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
 @Override public void onStart(){Bundle result=new Bundle();Activity activity=null;try{
  Intent intent=new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);activity=startActivitySync(intent);SystemClock.sleep(2500);Activity a=activity;runOnMainSync(()->view=(GoldenCloverView)((ViewGroup)a.findViewById(android.R.id.content)).getChildAt(0));Field f=GoldenCloverView.class.getDeclaredField("g");f.setAccessible(true);state=(GameState)f.get(view);Field loaded=GoldenCloverView.class.getDeclaredField("loaded");loaded.setAccessible(true);directory=new File(getTargetContext().getFilesDir(),"qa");directory.mkdirs();long deadline=SystemClock.uptimeMillis()+30000;while(!loaded.getBoolean(view)&&SystemClock.uptimeMillis()<deadline)SystemClock.sleep(200);check(loaded.getBoolean(view),"graphics loaded");Field af=GoldenCloverView.class.getDeclaredField("audio");af.setAccessible(true);AudioManager audio=(AudioManager)af.get(view);deadline=SystemClock.uptimeMillis()+60000;while(audio.readyCount()<16&&SystemClock.uptimeMillis()<deadline)SystemClock.sleep(100);check(audio.readyCount()==16,"16 sound samples loaded");check(view.getHeight()>view.getWidth(),"portrait orientation");check(state.credit==2000,"fresh launch is $2,000");shot("base");
  tap(360,1090);check(state.ui.betMenu,"bet opens");shot("bet-menu");tap(360,605);check(state.bet.value==20&&!state.ui.betMenu,"select $20");boolean sound=state.ui.sound;tap(515,1178);check(state.ui.sound!=sound,"sound toggle");tap(515,1178);tap(360,1178);check(state.phase==GameState.Phase.SPIN,"native spin touch");shot("spin");deadline=SystemClock.uptimeMillis()+20000;while(state.phase==GameState.Phase.SPIN&&SystemClock.uptimeMillis()<deadline)SystemClock.sleep(100);check(state.reels.stopped==5,"all reels stop");
  runOnMainSync(()->{state.resetSession();state.credit=.5;});tap(78,1178);check(!state.ui.auto&&state.credit==.5,"insufficient funds stop auto");runOnMainSync(()->state.resetSession());
  tap(640,1178);check(state.ui.featureMenu,"free demo chooser");shot("demo-menu");tap(360,480);check(state.phase==GameState.Phase.BOUNCE&&state.bonus.mask==1&&state.credit==2000,"free Blaze starts without charge");SystemClock.sleep(550);shot("feature-trigger");deadline=SystemClock.uptimeMillis()+20000;while(state.phase==GameState.Phase.BOUNCE&&SystemClock.uptimeMillis()<deadline)SystemClock.sleep(100);check(state.bonus.blazeCell>=0,"Blaze selected clover");shot("blaze");
  runOnMainSync(()->{state.resetSession();state.demoBonus(2);state.phase=GameState.Phase.BONUS;state.time=0;});shot("jackpot");check(state.bonus.cells==30,"double-reel Jackpot board");
  runOnMainSync(()->{state.resetSession();state.demoBonus(4);state.phase=GameState.Phase.BONUS;state.time=0;});shot("bomb");
  runOnMainSync(()->{state.resetSession();state.demoBonus(7);state.phase=GameState.Phase.BONUS;state.time=0;});shot("all-features");
  runOnMainSync(()->{state.phase=GameState.Phase.WIN;state.time=1;state.win=300;});shot("mega-win");
  runOnMainSync(()->{state.phase=GameState.Phase.BONUS_END;state.time=1;state.win=10000;state.bonus.grand=true;});shot("grand");
  tap(200,1178);check(state.ui.menu,"rules open during celebration");tap(360,866);check(state.credit==2000&&state.phase==GameState.Phase.IDLE&&!state.ui.menu,"reset cancels feature and restores balance");
  runOnMainSync(()->{state.credit=123;state.ui.auto=true;a.moveTaskToBack(true);});SystemClock.sleep(500);getTargetContext().startActivity(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));SystemClock.sleep(1000);check(state.credit==2000&&!state.ui.auto&&state.phase==GameState.Phase.IDLE,"foreground entry starts fresh $2,000 session");shot("fresh-session");
  result.putString("stream","PASS: Android portrait, touches, 16 audio samples, all three features, free previews, double reels and $2,000 foreground reset "+preset+"\n");finish(Activity.RESULT_OK,result);
 }catch(Throwable e){result.putString("stream","FAIL: "+e.toString()+"\n");finish(Activity.RESULT_CANCELED,result);}finally{if(activity!=null)activity.finish();}}
}
